repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0 # this specifies the version
    hooks:
     - id: fmt
       args: ["--manifest-path", "backend/Cargo.toml", "--"]
     - id: cargo-check
       args: ["--manifest-path", "backend/Cargo.toml"]
     - id: clippy 
       args: ["--manifest-path", "backend/Cargo.toml"]



 # - repo: https://github.com/rustsec/cargo-audit
  #  rev: main  # this specifies the version
   # hooks:
   #   - id: cargo-audit
   #     name: Cargo Audit (Dependency security check)
    #    language_version: system
    #    files: Cargo.toml
