repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0 # this specifies the version
    hooks:
     - id: fmt
       args: ["--manifest-path", "backend/Cargo.toml", "--"]
     - id: cargo-check
       args: ["--manifest-path", "backend/Cargo.toml"]
     - id: clippy 
       args: ["--manifest-path", "backend/Cargo.toml"]

