services:
  app:
    image: alekomom/whoknows:latest
    command: sh -c "sleep 10 && /app/backend"
    ports:
      - "8080:8080"
    restart: no 
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1

    volumes:
      - app_logs:/app/logs

volumes:
  app_logs:
