version: '3.8'

services:
  rust-app:
    build: .
    container_name: rust-app
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/var/log
      # Optional: Persist git repo between container restarts
      - git-data:/whoknows
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    # Necessary for proper signal handling
    init: true

volumes:
  # Optional: Uncomment if you want to persist git data
  git-data:

