

services:
  rust-app:
    build: .
    container_name: rust-app
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/var/log/supervisor
      - ./src:/whoknows/src  # for dev (optional)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
