services:
  app:
    image: alekomom/whoknows:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1

    volumes:
      - app_logs:/app/logs

volumes:
  app_logs:
