name: Build and Deploy

on:
  push:
    branches: [ test2/updating_mechanism ]  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: alekomom/whoknows:latest
        
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        timeout: 60s
        script_stop: true
        script: |
          cd ~/whoknows-deployment
          
          # Force stop any containers using port 8080
          echo "Stopping any services using port 8080..."
          docker ps | grep "0.0.0.0:8080" | awk '{print $1}' | xargs -r docker stop
          
          # Make sure all containers from the compose file are down
          docker-compose down --remove-orphans
          
          # Wait a moment to ensure ports are released
          sleep 5
          
          # Pull and start the updated containers
          docker-compose pull
          docker-compose up -d 
