# .github/workflows/rust-linter.yml

name: Rust Linter

on:
  pull_request:
    branches:
      - development  # Or 'development', or your primary branch
  workflow_dispatch:

jobs:
  lint-rust:
    name: Lint Rust Code
    runs-on: ubuntu-latest
    permissions:
      contents: read        # To check out the code
      pull-requests: write  # To post review comments and create reviews
      checks: write         # To create check runs (used by some reviewdog reporters)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch enough history for linters that diff against the base branch

      # Optional: Cache super-linter internal cache if needed to speed up subsequent runs
      # - name: Cache Super-Linter internal cache
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.cache/super-linter
      #     key: ${{ runner.os }}-super-linter-${{ github.sha }}  # Cache per commit
      #     restore-keys: |
      #       ${{ runner.os }}-super-linter-

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1  # Pinning to v1 for stability
        with:
          reviewdog_version: latest  # Or pin to a specific version e.g., v0.17.3

      # *** NEW STEP: Manually run cargo clippy for debugging ***
      - name: Debug - Manually run cargo clippy
        run: |
          echo "### Running cargo clippy manually from $(pwd)"
          rustc --version
          cargo --version
          cargo clippy --all-targets -- -D warnings # Fail on warnings
        # Optional: Add continue-on-error if you want the workflow to proceed even if this fails
        # continue-on-error: true

      - name: Run Super-Linter for Rust
        uses: super-linter/super-linter@v7
        continue-on-error: true
        env:
          # ... (rest of Super-Linter env vars as before)
          # Let's try VALIDATE_ALL_CODEBASE: true just in case the file filtering is involved
          VALIDATE_ALL_CODEBASE: true # Try forcing validation of all files
          # DEFAULT_BRANCH: main # Not needed if VALIDATE_ALL_CODEBASE=true

      - name: Run reviewdog with SARIF Results
        if: always()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running reviewdog with SARIF file: results.sarif"

          # Check if the SARIF file exists and is not empty before running reviewdog
          if [[ ! -s "results.sarif" ]]; then
            echo "results.sarif not found or is empty. Skipping reviewdog."
            exit 0
          fi

          reviewdog -f=sarif \
            -name="rust-linter" \
            -reporter="github-pr-review" \
            -filter-mode="diff_context" \
            -fail-level="warning" \
            -level="warning" \
            results.sarif
