name: Rust Linter

on:
  pull_request:
    branches:
      - development  
  workflow_dispatch:   

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint-rust:
    name: Lint Rust Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

      - name: Run review dog
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]

      
