name: Linter
on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - development
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      # Add the cache step here
      - name: Cache Super-Linter
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/super-linter
            .github/linters
          key: ${{ runner.os }}-super-linter-${{ hashFiles('**/.github/super-linter.env') }}
          restore-keys: |
            ${{ runner.os }}-super-linter-

      - name: Setup reviewdog
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: latest

      - name: Run Super-linter
        uses: super-linter/super-linter@v7.3.0
        id: super-linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: false
          OUTPUT_FORMAT: "tap"
          LOG_LEVEL: "ERROR"
          OUTPUT_DETAIL: "detailed"
          VALIDATE_RUST_2021: true
          VALIDATE_RUST_CLIPPY: true
          VALIDATE_ALL_CODEBASE: true
          # Don't use GITHUB_COMMENT since we'll use reviewdog for that
          GITHUB_COMMENT: false
          # Enable file creation for reviewdog to process
          CREATE_LOG_FILE: true
          LOG_FILE_PATH: "super-linter-logs"

      - name: Run reviewdog
        if: always()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Add debug output to see what files exist
          echo "Checking for TAP files in the logs directory"
          find $GITHUB_WORKSPACE/super-linter-logs -type f -name "*.tap" || echo "No TAP files found"
          
          # Process the TAP format logs from super-linter and feed to reviewdog
          find $GITHUB_WORKSPACE/super-linter-logs -name "*.tap" -type f | while read file; do
            echo "Processing $file"
            linter_name=$(basename "$file" .tap)
            cat "$file" | reviewdog -f=tap -name="${linter_name}" -reporter=github-pr-review
          done