name: Linter
on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - development
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      # Add the cache step here
      - name: Cache Super-Linter
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/super-linter
            .github/linters
          key: ${{ runner.os }}-super-linter-${{ hashFiles('**/.github/super-linter.env') }}
          restore-keys: |
            ${{ runner.os }}-super-linter-

      - name: Setup reviewdog
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: latest

      - name: Run Super-linter
        uses: super-linter/super-linter@v7.3.0
        id: super-linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: false
          OUTPUT_FORMAT: "tap"
          LOG_LEVEL: "ERROR"
          OUTPUT_DETAIL: "detailed"
          VALIDATE_RUST_2021: true
          VALIDATE_RUST_CLIPPY: true
          VALIDATE_ALL_CODEBASE: true
          GITHUB_COMMENT: false
          CREATE_LOG_FILE: true
        continue-on-error: true

      - name: Capture linter output
        if: always()
        run: |
          mkdir -p /tmp/linter-output
          echo "${{ steps.super-linter.outputs.stdout }}" > /tmp/linter-output/stdout.txt
          echo "${{ steps.super-linter.outputs.stderr }}" > /tmp/linter-output/stderr.txt

      - name: Run reviewdog
        if: always()
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat /tmp/linter-output/stdout.txt | reviewdog -f=tap -name="super-linter" -reporter=github-pr-review