name: Rust Linter

on:
  pull_request:
    branches:
      - development  
  workflow_dispatch:   

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint-rust:
    name: Lint Rust Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
        continue-on-error: true

      - name: Install clippy-reviewdog-filter
        run: |
          curl -L -o /tmp/clippy-reviewdog-filter https://github.com/qnighy/clippy-reviewdog-filter/releases/latest/download/clippy-reviewdog-filter-x86_64-unknown-linux-gnu
          chmod +x /tmp/clippy-reviewdog-filter
          
      - name: Run reviewdog with clippy-reviewdog-filter
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
          
      - name: Report Clippy results with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat clippy-output.txt | /tmp/clippy-reviewdog-filter | reviewdog -f=rdjson -reporter=github-pr-review

      
