name: Verify Secret Hash
on:
  workflow_dispatch:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate hash
        run: |
          echo "${{ secrets.DEV_ENV_FILE }}" | sha256sum | cut -d' ' -f1 > secret_hash.txt
          echo "Secret hash: $(cat secret_hash.txt)"
